easy_admin:
    design:
        menu: 
            - { entity: 'User', default: true }
            - Wish
            - Gift
            - Positionning
        
    entities:
        # List the entity class name you want to manage
            User:
                    class: App\Entity\User
            Wish:
                    class:  App\Entity\Wish
            Gift: 
                    class: App\Entity\Gift
            Positionning:
                    class:  App\Entity\Positionning
